Added QoL updates to Han shape-based layout
Waelwindows/florisboard pull request #1
Opened 2022-09-21 06:47 UTC by moonbeamcelery

Separate the space behavior of the new nlp providers and the regular Latin ones, and expose setting nlp providers to the subtype editor. These allow Latin layouts and the new layout to coexist.

TODO: switching subtypes with different nlp providers currently does not reset suggestions, so you would still have suggestions from another language until you type or move your cursor.

2022-09-21 07:06 UTC, moonbeamcelery commented
Note: also included is avoiding suggestions when the composed text is empty (instead of suggesting characters for a, aa, aaa, etc.)

2022-09-21 13:37 UTC, Waelwindows reviewed
This would better as a separate PR

2022-09-21 13:56 UTC, Waelwindows requested changes

2022-09-21 13:56 UTC, Waelwindows commented on app/src/main/kotlin/dev/patrickgold/florisboard/ime/editor/EditorInstance.kt
> +        // TODO: maybe put this recurring condition in a function that determines CJK
It's better to add this function in this PR

2022-09-21 14:09 UTC, Waelwindows commented on app/src/main/kotlin/dev/patrickgold/florisboard/ime/editor/EditorInstance.kt
> +        // TODO: maybe put this recurring condition in a function that determines CJK
Perhaps look into adding it to `FlorisLocale.kt`?

2022-09-21 14:49 UTC, moonbeamcelery commented
> This would better as a separate PR

You mean the one where avoiding suggestions when composing text is empty?

2022-09-21 14:54 UTC, Waelwindows commented
> > This would better as a separate PR
> 
> You mean the one where avoiding suggestions when composing text is empty?

Sorry for not being clear. I'm new to GitHub's review process. 

I meant the suggestion provider UI

2022-09-22 07:22 UTC, moonbeamcelery commented on app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/KeyboardManager.kt
> +        // TODO: maybe put this recurring condition in a function that determines CJK
TODO: delet this

2022-09-22 07:23 UTC, moonbeamcelery commented
Updated with suggested changes. The editor change will be another one, although I couldn't get it to work now that the db is dependent on primaryLocale.variant

2022-09-22 09:20 UTC, Waelwindows commented
> Updated with suggested changes. The editor change will be another one, although I couldn't get it to work now that the db is dependent on primaryLocale.variant

Did you try with the zh-RC-zhengma layout?

2022-09-22 16:37 UTC, moonbeamcelery commented
> > Updated with suggested changes. The editor change will be another one, although I couldn't get it to work now that the db is dependent on primaryLocale.variant
>
> Did you try with the zh-RC-zhengma layout?

~I couldn't find it~
Ok I found it. I left a comment in your pr regarding this.

Edit: confirmed it works. Thank you!

2022-09-23 20:56 UTC, Waelwindows approved these changes

2022-10-15 04:30 UTC, moonbeamcelery commented
Hello again Waelwindows, is there anything I can help with getting your PR merged? Would making a Chinese layout be helpful for example? I really appreciate your work and would love to see this update on the main repo soon!

2022-10-21 18:06 UTC, Waelwindows commented
Adding more layouts would be great! 

Wish I could work more on FlorisBoard but as uni student, exam season never seems to be away for too long :sweat_smile:.

For now, I think it's good to get other tables from [fcitx5-tables-extra](https://github.com/fcitx/fcitx5-table-extra) as the data from there is from the public domain (or so they claim).

I should probably do that for zhengma as well, since I got that from `ibus-zhengma` which i'm not sure uses public domain tables

2022-10-21 19:43 UTC, Waelwindows commented
I have looked into the PR and it seems that we've forgotten to invert the condition :joy:.

Although there's another problem now, after committing the suggestion, a space is added when you write a letter. Gotta look into that.

2022-10-21 19:54 UTC, Waelwindows commented
Got it, kinda weird that I had to negate all uses of it, perhaps the meaning was flipped in my implementation?

2022-10-21 19:57 UTC, merged

2022-10-23 06:59 UTC, moonbeamcelery commented
Oops, sorry I didn't see this one, lol.

Yeah, it used to be `isCJK` which would indeed be `!supportAutoSpace`.

2022-10-23 06:59 UTC, moonbeamcelery commented
> Adding more layouts would be great!
> 
> Wish I could work more on FlorisBoard but as uni student, exam season never seems to be away for too long sweat_smile.
> 
> For now, I think it's good to get other tables from [fcitx5-tables-extra](https://github.com/fcitx/fcitx5-table-extra) as the data from there is from the public domain (or so they claim).
> 
> I should probably do that for zhengma as well, since I got that from `ibus-zhengma` which i'm not sure uses public domain tables.
> 
> Perhaps the above as different PRs? Hopefully i'll respond to them on time

Got it, I'll try some of these when I have time.